### PR TITLE
Image Formats overhaul

### PR DESCRIPTION
**Pull request by lqueiroga**

### CODE REVIEW

**Comment by lqueiroga** [comment]
Trying to change commands "targetFormat" by "target-format" raise an error in CLI 
Below the stacktrace of the error:
uforge-cli >org target-format
*** Command not found: target -format

**Comment by jbremond** [comment]
Thanks for this info. I'm going to log a RFE to support this.

Joris

**Comment by jbremond** [comment]
The issue is #5

**Comment by jbremond** [comment]
Due to a commit --amend, all comments has been lost. I merge the pull request because the comments has been taken into account (even if we have lost the trace)

**Pull request merged**
